### ISSUE TITLE
Consider making "channel" optional in NimbusExperiment schema

### ISSUE THREAD

**Issue by rfk** [mozilla/nimbus-shared#125]
The [channel property](https://github.com/k88hudson/nimbus-shared/blob/fb9bacac84fedd6c268621add00966775b6c9dd2/types/experiments.ts#L42) is currently required to be an array of strings. Some applications (e.g. reference-browser) may not have a useful notion of channels, and it's not obvious what we should put in that field in that case. Setting it to an empty array risks being interpreted as "don't run in any channels".

**Comment by rfk** [comment]
For completeness, noting that IIUC the example in https://github.com/k88hudson/nimbus-shared/blob/fd5a6eaa321086edbefff123c388a3151b26a58f/data/experiment-recipe-samples/mobile-a-a.json doesn't validate against the current schema because it doesn't have the "channels" field.

**Comment by k88hudson** [comment]
Sorry for the incorrect references here – this was actually fixed by https://github.com/mozilla/nimbus-shared/commit/fb38808b0ae6e6f84e0a74e9592156ea73e595a9. I decided to remove channel as a top-level property until we can sort out some complexity around unbranded builds etc.
