### ISSUE TITLE
Clarify whether "number" fields are ints or floats

### ISSUE THREAD

**Issue by rfk** [mozilla/nimbus-shared#126]
The schema is in typescript, which only has a single `number` type that is a float by default. Are any of the fields in the `Experiment` schema expected to be floats in practice, or will they always be integers? I'm wondering particularly about the `[ratio](https://github.com/k88hudson/nimbus-shared/blob/fb9bacac84fedd6c268621add00966775b6c9dd2/types/experiments.ts#L77)` field, but it will be useful to clarify this in general.

(Many languages won't care about this in practice, but the Rust client definitely will, and it won't really tolerate a float where it's expecting an int)

**Comment by k88hudson** [comment]
Interestingly as per https://bugzilla.mozilla.org/show_bug.cgi?id=1659419 Remote Settings is planning on disallowing floats (at least for awhile, until all supported clients can be updated to the new implementation). I'll add some validation annotations for this
