### ISSUE TITLE
Clarify semantics of `proposedEnrollment` and `proposedDuration` fields

### ISSUE THREAD

**Issue by rfk** [mozilla/nimbus-shared#129]
It's not clear whether the `proposedEnrollment` and `proposedDuration` are for consumption by the client SDKs, experimenter, jetstream, or something else. Does the client SDK need to interpret these in any way or change behaviour based on them?

**Comment by k88hudson** [comment]
Fixed by https://github.com/mozilla/nimbus-shared/commit/9a74dde37cbfb73dacd49e8daa66b66cb013619b
