### ISSUE TITLE
Publish some Features to Python consumers

### ISSUE THREAD

**Issue by tdsmith** [mozilla/nimbus-shared#39]
Once we have a schema for some Features (#38) we should have infrastructure for making them available to consumers.

Some questions:
- What language is used to specify Features? (Opening bid: TOML, for flexibility, but something else that gets translated to JSON at build should be workable.)
- What does the Python API for data access look like?

**Comment by mythmon** [comment]
> What language is used to specify Features? (Opening bid: TOML, for flexibility, but something else that gets translated to JSON at build should be workable.)

My requirements for specifying data are:

1. Human readable/writable
2. Machine convertible to JSON
3. Can be type checked
4. Can specify the type that the data is

1 and 2 are pretty easy, and TOML fulfills.

The only format I can think of that natively supports 4 is Typescript. We can add support to that for other formats too though. There are some discussions about adding it to TOML as well.

For the time being, I suggest we use TOML and declare that everything in the `data/features/` directory must be of a single type (`FeatureDefinition` maybe?). If this ends up being too restrictive, we can explore other options like tagging the data with a special key.

**Comment by tdsmith** [comment]
> What does the Python API for data access look like?

https://github.com/altair-viz/schemapi is a tool for generating Python classes from a jsonschema spec, which could be nice.

**Comment by mythmon** [comment]
I believe this is done now, accessible through `mozilla_nimbus_shared.data.features` in Python.

Nicer APIs that are based on potentially auto-generated classes could be interesting, but maybe lets look at that after we get some experience using the library.
