### ISSUE TITLE
Confirm npm and PyPi have enough collaborators set

### ISSUE THREAD

**Issue by pdehaan** [mozilla/nimbus-shared#51]
You know, [bus factor](https://en.wikipedia.org/wiki/Bus_factor) and all that...
Plus, this way we always have the ability to deploy updates if somebody is on PTO.

**Comment by mythmon** [comment]
NPM and PyPI both notw have two owners, myself and the `project-nimbus-publishing` automated account. @pdehaan is that enough for your liking? If not, are there any volunteers?

**Comment by pdehaan** [comment]
@mythmon Who's the owner/contact of the "project-nimbus-publishing" automated account? OPs?

Two people seems good enough to satisfy the "somebody is on PTO or dead" concern.
Mr @jaredlockhart, does this sound OK to you, or do you/Rehan/Tif want to be module co-owners in case we need an emergency/off-schedule module publish?

**Comment by mythmon** [comment]
See #52 for details about the automated account. In short a mailing list owns it, and I've been doing the account set up for it. There will be docs for this included in the patch for #52.

**Comment by pdehaan** [comment]
#52 plan sounds awesome. Closing. ❤️
