### ISSUE TITLE
Auto deploy npm/pypi packages on tag

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/nimbus-shared#52]
Can we set it up to automatically publish those packages when a new tag is committed so that nobody needs any special permissions to publish updates?

---

We're doing this using a shared account linked to a mailing list. Here's what we need to do:

- [x] Set up the mailing list
- [x] Make a PyPI account with access to the package
- [x] Make an NPM account with access to the package
- [x] Add credentials for the above to CircleCI
- [x] Set up CircleCI to auto deploy tags
- [x] Document it all
- [x] Demonstrate it actually working

**Comment by mythmon** [comment]
One of the complications with automatic publishing is that both PyPI and NPM require a specific user account to publish. PyPI at least allows you to use an API token that is scoped to a particular project, but for NPM it would mean having access to anything that the account has.

That implies we need to create an account just for publishing, that would have a shared email address and a shared password. We can use a mail group for the email. I'm not sure how to manage the shared password. We don't really have tools to do that right now.

**Comment by pdehaan** [comment]
Let's just use the password "bananas1".

**Comment by mythmon** [comment]
I hope that was a joke, Peter.

**Comment by jaredlockhart** [comment]
Ya good call making a dedicated user account for both, I'm sure we can get ops to set something up and put the passwords in their secret managers and then store them in circle the way they do for like dockerhub creds now.  Actually that's a good point, who should be the ops person for nimbus?

**Comment by tdsmith** [comment]
This is going to be critical for keeping a tight loop between data updates and downstream deployments.

I think we could manage without sharing secrets.

The PyPI case seems straightforward; packages can and should have n owners and if someone gets hit by a bus we can just get one of the other owners to generate a token.

We could use orgs in a similar way on npm; we could add human members to the org as admins, someone could create a role account with their own contact information that has write permissions, and we could use that role account's token in CD. The recovery procedure would be to spin up a new role account.

**Comment by mythmon** [comment]
After talking with the CloudOps team about this, we're going to use a shared Google Group as the email for publishing accounts. This will be specifically for deployment accounts, and not have other traffic on it. The password for the account doesn't need to be stored in a shared place because if it is needed an inaccessible, we can use the password reset flow. If somehow we have full turn over and no one is left with access to the account, IT can edit it to add a new admin to the group.

**Comment by mythmon** [comment]
v0.0.7 was deployed automatically using this technique!
