### ISSUE TITLE
Where are experiment duration and enrollment duration expressed?

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/nimbus-shared#68]
I just realized our design preset doesn't include the duration information:

https://github.com/mozilla/nimbus-shared/blob/main/data/ExperimentDesignPresets.ts#L18-L33

**Comment by pdehaan** [comment]
I think the Experiment model defines a `startDate`, `endDate`, and `proposedEnrollment` duration here:

https://github.com/mozilla/nimbus-shared/blob/87fbe0ed7ee31f421574bd749634e5c8e969191b/types/experiments.ts#L37-L48

**Comment by jaredlockhart** [comment]
Yeah what we need to store on the design is

experiment duration
enrollment duration



From @tdsmith for A/A we'll use:

experiment duration: 28 days
enrollment duration: 7 days
