### ISSUE TITLE
Add jexl template for targeting string

### ISSUE THREAD

**Issue by k88hudson** [mozilla/nimbus-shared#73]

**Comment by jaredlockhart** [comment]
From chatting with @k88hudson it looks like we need a string template to use to generate the JEXL expression for all experiments that needs to include

* firefox version
* bucket sample
* the audience string


so I imagine it looking something like 

```js
export const JEXL_EXPRESSION = "firefoxVersion >= {firefoxVersion} && bucketsample({bucketStart}, {bucketEnd}, {bucketCount}, {bucketNamespace}) && {audienceJexl}"
```

which experimenter can then consume and emit as parts of its recipe.

**Comment by jaredlockhart** [comment]
It could even go as a constant in here:

https://github.com/mozilla/nimbus-shared/blob/main/data/ExperimentDesignPresets.ts

and just be passed through the 

https://github.com/mozilla/nimbus-shared/blob/main/types/experiments.ts#L9

field in the design preset

**Comment by mythmon** [comment]
Lessons from Normandy: Please don't use `>=` for version comparison. Please use the JEXL `versionCompare` filter which properly handles things like dot releaes, beta versions, and our eventual cross into 3 digit version numbers. [Example usage here](https://github.com/mozilla/normandy/blob/3bb1b278878b8e92f9958fb414d835ce876e6d43/normandy/recipes/filters.py#L666). To translate Jared's mock JEXL it would be something like

```js
export const JEXL_EXPRESSION = "firefoxVersion|versionCompare("{firefoxVersion}") >= 0 && [userId, bucketNamespace]|bucketsample({bucketStart}, {bucketCount}, {totalBuckets}) && {audienceJexl}"
```

**Comment by k88hudson** [comment]
I moved some of this discussion to [a doc](https://docs.google.com/document/d/18RdsFtCX4p-eKPPqqihCCwcbTJnhBvuB6Vy_E4qzGEk/edit#) since there are some different things to consider here

**Comment by jaredlockhart** [comment]
@mythmon thnx for the proper JEXL translation.  Will that JEXL expression work with the targeting that nimbus uses in Experiment Manager (x-man)? 

Also I think that there are two targeting expressions in nimbus, one for Remote Settings and one for Experiment Manager?  Or one for messaging system?  I'm not sure what the distinction between the two is @k88hudson ?

https://github.com/mozilla/nimbus-shared/blob/main/types/experiments.ts#L8-L13

**Comment by mythmon** [comment]
>  Will that JEXL expression work with the targeting that nimbus uses in Experiment Manager (x-man)?

I haven't tested it, and I don't the details of the x-man targeting environment yet. I suspect I got the variable names wrong, but the rest should be fine.

**Comment by k88hudson** [comment]
Ok, after taking a look at the discussion I think it makes sense to go with `versionCompare` – however, we'll need to use the `filter_expression` property for versions <80 (until Andrei's patch lands https://phabricator.services.mozilla.com/D79967):

i.e.

```
{
  filter_expression: "env.version|versionCompare('{minFirefoxVersion}') >= 0 && {audience.filter_expression}",
  targeting: "[{randomizationUnit}, {bucketNamespace}]|bucketSample({bucketStart}, {bucketCount}, {totalBuckets}) && {audience.filter_expression}"
}
```

FWIW i don't think this makes a lot of sense to live in this repo (I think it would be better expressed in a serializer with something like filter expressions as the input), but as long as this goes through a QA process, I think we can try it

**Comment by jaredlockhart** [comment]
> Ok, after taking a look at the discussion I think it makes sense to go with `versionCompare` – however, we'll need to use the `filter_expression` property for versions <80 (until Andrei's patch lands https://phabricator.services.mozilla.com/D79967):
> 
> i.e.
> 
> ```
> {
>   filter_expression: "env.version|versionCompare('{minFirefoxVersion}') >= 0 && {audience.filter_expression}",
>   targeting: "[{randomizationUnit}, {bucketNamespace}]|bucketSample({bucketStart}, {bucketCount}, {totalBuckets}) && {audience.targeting}"
> }
> ```
> 
> FWIW i don't think this makes a lot of sense to live in this repo (I think it would be better expressed in a serializer with something like filter expressions as the input), but as long as this goes through a QA process, I think we can try it

@k88hudson so this refers to `audience.filter_expression`, but I only see `audience.targeting` on the audience definitions we have now:

https://github.com/mozilla/nimbus-shared/blob/main/data/Audiences.ts#L7

is that something we'd have to add to audiences?

**Comment by k88hudson** [comment]
@jaredlockhart `filter_expression` is an optional property right now (but it hasn't been needed yet) https://github.com/mozilla/nimbus-shared/blob/main/types/targeting.ts#L5
